name: MultiColumnWizard

on:
  push:
    branches-ignore:
      - '**-translation'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - contao:        '~5.1.0'
            php:           '8.1'
            phpcq_install: 'update'
            phpcq_flags:   ''
          - contao: '~5.1.0'
            php: '8.2'
            phpcq_install: 'update'
            phpcq_flags: ''

    steps:
      - name: PHP ${{ matrix.php }} ${{ matrix.contao }} Pull source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see https://github.com/shivammathur/setup-php
      - name: PHP ${{ matrix.php }} ${{ matrix.contao }} Setup PHP.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage:    none

      - name: PHP ${{ matrix.php }} ${{ matrix.contao }} Cache composer cache directory
        uses: actions/cache@v1
        env:
          cache-name: composer-cache-dir-${{ matrix.php }}-${{ matrix.contao }}
        with:
          path: ~/.cache/composer
          key:  ${{ runner.os }}-build-${{ env.cache-name }}

      - name: PHP ${{ matrix.php }} ${{ matrix.contao }} Cache vendor directory
        uses: actions/cache@v1
        env:
          cache-name: composer-vendor-${{ matrix.php }}-${{ matrix.contao }}
        with:
          path:         vendor
          key:          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: PHP ${{ matrix.php }} ${{ matrix.contao }} Install composer dependencies
        run:  composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable

      - name: PHP ${{ matrix.php }} Update phpcq
        run:  ./vendor/bin/phpcq self-update --unsigned

      - name: PHP ${{ matrix.php }} Install phpcq toolchain
        run:  ./vendor/bin/phpcq ${{ matrix.phpcq_install }} -v

      - name: PHP ${{ matrix.php }} ${{ matrix.contao }} Run tests
        run:  ./vendor/bin/phpcq run -v -o github-action -o default ${{ matrix.phpcq_flags }}

      - name: PHP ${{ matrix.php }} ${{ matrix.contao }} Upload build directory to artifact
        uses: actions/upload-artifact@v2
        if:   ${{ success() }} || ${{ failure() }}
        with:
          name: phpcq-builds-php-${{ matrix.php }}-${{ matrix.contao }}
          path: .phpcq/build/
